In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("car data.csv")
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [3]:
df.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [4]:
df.shape

(301, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [6]:
df.isnull()

Car_Name   Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0       False  False          False          False       False      False   
1       False  False          False          False       False      False   
2       False  False          False          False       False      False   
3       False  False          False          False       False      False   
4       False  False          False          False       False      False   
..        ...    ...            ...            ...         ...        ...   
296     False  False          False          False       False      False   
297     False  False          False          False       False      False   
298     False  False          False          False       False      False   
299     False  False          False          False       False      False   
300     False  False          False          False       False      False   

     Seller_Type  Transmission  Owner  
0          False         False  False  
1          False         False  False  
2          False         False  False  
3          False         False  False  
4          False         False  False  
..           ...           ...    ...  
296        False         False  False  
297        False         False  False  
298        False         False  False  
299        False         False  False  
300        False         False  False  

[301 rows x 9 columns]

In [7]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

# Replacing text with numeric values

In [8]:
df.replace({'Fuel_Type':{'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)
df.replace({'Seller_Type':{'Dealer':0,'Individual':1}},inplace=True)
df.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

In [9]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0     ritz  2014           3.35           5.59       27000          0   
1      sx4  2013           4.75           9.54       43000          1   
2     ciaz  2017           7.25           9.85        6900          0   
3  wagon r  2011           2.85           4.15        5200          0   
4    swift  2014           4.60           6.87       42450          1   

   Seller_Type  Transmission  Owner  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0

# Spliting dataset and target

In [10]:
X = df.drop(['Car_Name','Selling_Price'],axis=1)
Y = df['Selling_Price']

In [11]:
X

Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
0    2014           5.59       27000          0            0             0   
1    2013           9.54       43000          1            0             0   
2    2017           9.85        6900          0            0             0   
3    2011           4.15        5200          0            0             0   
4    2014           6.87       42450          1            0             0   
..    ...            ...         ...        ...          ...           ...   
296  2016          11.60       33988          1            0             0   
297  2015           5.90       60000          0            0             0   
298  2009          11.00       87934          0            0             0   
299  2017          12.50        9000          1            0             0   
300  2016           5.90        5464          0            0             0   

     Owner  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
296      0  
297      0  
298      0  
299      0  
300      0  

[301 rows x 7 columns]

In [12]:
Y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

# Splitting Training and Test data

In [13]:
from sklearn.model_selection import train_test_split



X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=50)

In [14]:
X_train

Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
264  2015           7.00       40026          0            0             0   
119  2013           1.90        5400          0            1             0   
288  2015          13.60       34000          0            0             0   
242  2014           7.13       34000          0            0             0   
33   2014           9.95       45000          1            0             0   
..    ...            ...         ...        ...          ...           ...   
70   2014           6.76       71000          1            0             0   
132  2017           0.95        3500          0            1             0   
289  2016          13.60       10980          0            0             0   
109  2017           1.47       11000          0            1             0   
176  2011           1.05       30000          0            1             0   

     Owner  
264      0  
119      0  
288      0  
242      0  
33       0  
..     ...  
70       0  
132      0  
289      0  
109      0  
176      0  

[240 rows x 7 columns]

# Model Training

In [15]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr = lr.fit(X_train,Y_train)  

In [16]:
lr.coef_

array([ 4.40536754e-01,  4.28151147e-01, -3.43618167e-06,  1.72714100e+00,
       -1.09633075e+00,  1.40150124e+00,  7.58852558e-01])

In [17]:
coefficients = pd.concat([pd.DataFrame(X_train.columns),pd.DataFrame(np.transpose(lr.coef_))], axis = 1)

coefficients

0         0
0           Year  0.440537
1  Present_Price  0.428151
2     Kms_Driven -0.000003
3      Fuel_Type  1.727141
4    Seller_Type -1.096331
5   Transmission  1.401501
6          Owner  0.758853

# Model Evaluation

In [18]:
lr.intercept_

-885.7737750091302

In [19]:
Y_pred = lr.predict(X_test)
Y_pred

array([ 2.40141538, 10.73970061,  1.93143448,  4.55331583,  2.44089157,
        0.8039481 , 16.73671515,  0.40683766,  6.49065881,  9.26726504,
        2.44262472,  2.81506953,  8.97202536,  1.48403745, -0.62641804,
        0.57339979, 10.01604114, -0.13611151,  6.22687175,  8.83997566,
        5.11993582, -0.17505366,  8.1114632 ,  2.71941097,  0.03877951,
        1.57198422, 20.27124145,  5.59611264,  6.76145156,  6.73257541,
        0.39997998,  6.85846474, -3.93519776,  3.95361374,  5.06508059,
       10.1967708 ,  2.89312081,  4.41151761,  4.3841719 ,  0.88506268,
        0.2016964 ,  7.81206424,  5.53563276,  4.32286589,  2.21338807,
        6.12128768,  7.06456475,  3.70731199,  3.37305417,  1.09206853,
        2.37344567,  2.05305554,  7.41937139,  1.02352645,  8.54745732,
       -0.3321762 , 14.0642603 ,  1.92976938,  4.19348811,  4.33281071,
        4.48709248])

In [20]:
Y_test

239     2.00
97     17.00
203     2.95
220     3.50
102     1.65
       ...  
66     19.75
178     0.35
217     3.15
234     5.50
219     4.50
Name: Selling_Price, Length: 61, dtype: float64

In [21]:
Y_error = Y_test - Y_pred
Y_error

239   -0.401415
97     6.260299
203    1.018566
220   -1.053316
102   -0.790892
         ...   
66     5.685740
178   -1.579769
217   -1.043488
234    1.167189
219    0.012908
Name: Selling_Price, Length: 61, dtype: float64

In [22]:
plt.scatter(Y_train)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title(" Actual Prices vs Predicted Prices")
plt.show()

In [23]:
Y_train

264     4.00
119     1.05
288     8.40
242     4.40
33      6.00
       ...  
70      3.95
132     0.75
289    10.11
109     1.20
176     0.35
Name: Selling_Price, Length: 240, dtype: float64

In [24]:
Y_pred

array([ 2.40141538, 10.73970061,  1.93143448,  4.55331583,  2.44089157,
        0.8039481 , 16.73671515,  0.40683766,  6.49065881,  9.26726504,
        2.44262472,  2.81506953,  8.97202536,  1.48403745, -0.62641804,
        0.57339979, 10.01604114, -0.13611151,  6.22687175,  8.83997566,
        5.11993582, -0.17505366,  8.1114632 ,  2.71941097,  0.03877951,
        1.57198422, 20.27124145,  5.59611264,  6.76145156,  6.73257541,
        0.39997998,  6.85846474, -3.93519776,  3.95361374,  5.06508059,
       10.1967708 ,  2.89312081,  4.41151761,  4.3841719 ,  0.88506268,
        0.2016964 ,  7.81206424,  5.53563276,  4.32286589,  2.21338807,
        6.12128768,  7.06456475,  3.70731199,  3.37305417,  1.09206853,
        2.37344567,  2.05305554,  7.41937139,  1.02352645,  8.54745732,
       -0.3321762 , 14.0642603 ,  1.92976938,  4.19348811,  4.33281071,
        4.48709248])